.pc
.TH CONJUGAR 1 "May 2025" "Version 0.8.6" "CONJUGAR Manual Page"
.SH NAME
conjugar \- conjugator of Brazilian Portuguese verbs
.SH SYNOPSIS
.B conjugar
[options]

.B conjugar
[output options] verb

.SH DESCRIPTION
.I conjugar
is a conjugator of Portuguese verbs as spoken in Brazil. The input must be in
UTF-8 and the output will be in UTF-8 regardless of the system settings.
.BR
The software is based on conjugue, which was written by Ricardo Ueda
Karpischek.

.SH OPTIONS
.TP
\-v, \-\-version
Show the version number and exits.
.TP
\-h, \-\-help
Show an usage message and exits.
.TP
\-t
Creates the files
.I list_of_paradigms
,
.I list_of_verbs
and
.I all_verbs
where all verbs in the data base are conjugated.
.SH OUTPUT OPTIONS
.TP
\-\-color
Use ANSI scape codes to colorize the output.
.TP
\-\-xml
Output with xml tags.
.TP
\-\-common
Conjugate the verb as most ordinary Brazilians do instead of following the
normative grammar.
.TP
verb
Conjugates
.I verb
at startup, output the result to screen and exits.

.SH "REPORTING BUGS"
Report bugs at
.BR https://github.com/jalvesaq/gconjugue/issues
.SH COPYRIGHT
Copyright \(co 2005-2017 Jakson A. Aquino
.br
CONJUGAR comes with ABSOLUTELY NO WARRANTY; it is Free Software under GNU GPL.
See the
.B copyright 
file for details.
.SH SEE ALSO
.PP conjugar home page:
.BR https://github.com/jalvesaq/gconjugue
.PP
.SH AUTHOR
.PP
This man page was written by Jakson Aquino.
