.pc
.TH GCONJUGUE 1 "May 2020" "Version 0.8.5" "GCONJUGUE Manual Page"
.SH NAME
gconjugue \- conjugator of Brazilian Portuguese verbs
.SH SYNOPSIS
.B gconjugue

.SH DESCRIPTION
.BR gconjugue
is a conjugator of Portuguese verbs as spoken in Brazil. It is based on
conjugue, which was written by Ricardo Ueda Karpischek.

.SH "REPORTING BUGS"
Report bugs at
.BR https://github.com/jalvesaq/gconjugue/issues
.SH COPYRIGHT
Copyright \(co 2005-2017 Jakson A. Aquino
.br
GCONJUGUE comes with ABSOLUTELY NO WARRANTY; it is Free Software under GNU GPL.
See the
.B copyright 
file for details.
.SH SEE ALSO
.PP gconjugue home page:
.BR https://github.com/jalvesaq/gconjugue
.PP
.SH AUTHOR
.PP
This man page was written by Jakson Aquino.
